app:
  cors:
    allowed-origins: []
    allowed-origin-patterns:
      - "*"
      - "https://localhost:*"
      - "https://127.0.0.1:*"
      - "http://localhost:*"
      - "http://127.0.0.1:*"

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
